name = "Serif"
license = "MIT"
licenselink = "https://github.com/JugglerX/hugo-serif-theme/blob/master/LICENSE"
description = "Serif is a modern business theme for Hugo. It contains content types for the archetypical business website. The theme is fully responsive, blazing fast and artfully illustrated."
homepage = "https://github.com/jugglerx/hugo-serif-theme"
tags = ["responsive","minimal","clean","business","company","bootstrap","zerostatic","personal","google analytics"]
features = ["services","team","about","contact"]
min_version = 0.51

[author]
  name = "Robert Austin"
  homepage = "https://www.zerostatic.io"